basePath: /
consumes:
- application/jaon
info:
  description: Documentation for Product API
  title: of Product API
  version: 1.0.0
paths:
  /products:
    get:
      description: Returns a list of products
      operationId: listProducts
      responses:
        "200":
          $ref: '#/responses/productsResponse'
      tags:
      - prodcuts
produces:
- application/json
schemes:
- http
swagger: "2.0"
